stages:
  - build
  - deploy-new-service

variables:
    projectid: "sonorous-mix-245813"
    service: "cloudrun-cicd"
    region: "us-central1"
    image_name: "cloudrun-cicd"
    
build-push-docker-job:
  stage: build
#  image: docker:latest
#  services:
#    - docker:dind
#  before_script:
#    - echo $GCP_CRED > ${HOME}/service_key.json
#    - cat ${HOME}/service_key.json | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - pwd
    - ls -la
#    - cd helloworld-ruby
#    - docker build -t gcr.io/$projectid/$image_name:latest .
#    - docker push gcr.io/$projectid/$image_name:latest
