stages:
  - build
  - deploy

variables:
    projectid: "sonorous-mix-245813"
    service: "birdsuzb-serverless"
    region: "europe-west1"
    image_name: "birdsuzb"
    ram: "512Mb"

build-push-docker-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    #authentificate docker to be able to push images
    - echo $GCP_CRED > service_key.json
    - cat service_key.json | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - docker build -t gcr.io/$projectid/$image_name:latest .
    - docker push gcr.io/$projectid/$image_name:latest

deploy-service-job:
  stage: deploy
  image: google/cloud-sdk  #use docker image with gcp sdk for this job
  before_script:
    # Write our GCP service account private key into a file
    - echo $GCP_CRED > service_key.json
  script:
    - gcloud auth activate-service-account --key-file service_key.json
    - gcloud run deploy $service --project $projectid --image gcr.io/$projectid/$image_name:latest --region $region --platform=managed --memory $ram --allow-unauthenticated
