default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 34.107.93.146
  port: 5432
  username: postgres
  password: postgres
  database: birds_production

development: &development
  <<: *default

test: &test
  <<: *default
  database: birds_test

production: &production
  <<: *default
  database: birds_production
  # If connecting via unix domain socket, specify the socket path as host
  host:  "https://34.107.93.146/cloudsql/birds-stage:europe-west3:birds-production"
