default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 34.107.93.146
  port: 5432
  username: postgres
  password: postgres
  database: birds_production

development: &development
  <<: *default

test: &test
  <<: *default
  database: birds_test

production: &production
  <<: *default
